### ISSUE TITLE
Update translation of content/fundamentals/execution-context.md up to EN-dbf366a

### ISSUE THREAD

**Issue by Lou8is** [Lou8is/docs.nestjs.fr#163]
See https://github.com/nestjs/docs.nestjs.com/compare/f15008b690d44ede2dc78f234482dea687d8ad44..dbf366a36ffc8a4ab1e441237d37d349afdb4803#diff-90f176e7f454190563345c0d81cdb679891b7f76855906d5acad9ab450df7c4a

**Comment by pacyL2K19** [comment]
@Lou8is 
I can pick this up and work on it this weekend
Any recommendations / suggestions before I get started?
