### ISSUE TITLE
Update translation of content/pipes.md up to EN-dbf366a

### ISSUE THREAD

**Issue by Lou8is** [Lou8is/docs.nestjs.fr#165]
See https://github.com/nestjs/docs.nestjs.com/compare/f15008b690d44ede2dc78f234482dea687d8ad44..dbf366a36ffc8a4ab1e441237d37d349afdb4803#diff-fec05631d3b3f88e27c64571d637320cf7c86bd43fe58d277a2446cb8d9c54fd

**Comment by pacyL2K19** [comment]
@Lou8is 
I can pick this up
