### ISSUE TITLE
Update translation of content/techniques/configuration.md to EN-dbf366a

### ISSUE THREAD

**Issue by Lou8is** [Lou8is/docs.nestjs.fr#167]
See https://github.com/nestjs/docs.nestjs.com/compare/f15008b690d44ede2dc78f234482dea687d8ad44..dbf366a36ffc8a4ab1e441237d37d349afdb4803#diff-5f9b0615a42c67b5b754572601ec6dc78c6d886b4746a579e8620ca2347e7fc3

**Comment by pacyL2K19** [comment]
@Lou8is 
I can pick this up too, I will find some time this week to work on a couple of issues
