### ISSUE TITLE
Update translation of content/techniques/compression.md to EN-900b99d

### ISSUE THREAD

**Issue by Lou8is** [Lou8is/docs.nestjs.fr#180]
See https://github.com/nestjs/docs.nestjs.com/compare/dbf366a36ffc8a4ab1e441237d37d349afdb4803...master#diff-fab570cd21feb682700dd05b54b4a7bf06e8daa8eaa902a79cf7805465f3e2af

**Comment by pacyL2K19** [comment]
@Lou8is 
I can pick this up next
