### ISSUE TITLE
Update translation of content/techniques/events.md to EN-900b99d

### ISSUE THREAD

**Issue by Lou8is** [Lou8is/docs.nestjs.fr#181]
See https://github.com/nestjs/docs.nestjs.com/compare/dbf366a36ffc8a4ab1e441237d37d349afdb4803...master#diff-bc69f1c57ad640a8e9221a791f0de97f6ded4c536de80ca1258a696cdc384cb7

**Comment by pacyL2K19** [comment]
@Lou8is 
I can pick this up next
