### ISSUE TITLE
Techniques - Validation

### ISSUE THREAD

**Issue by Lou8is** [Lou8is/docs.nestjs.fr#36]

**Comment by lisa-sce** [comment]
@Lou8is assign me pls 🚀

**Comment by Lou8is** [comment]
Just checking, are you still on it?

**Comment by lisa-sce** [comment]
c'est bien ca? https://docs.nest-js.fr/techniques/validation

**Comment by lisa-sce** [comment]
on a deja mergé ou je confonds?

**Comment by Lou8is** [comment]
Tu as complétement raison, my bad. Je close !
